name: smart_fuel
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  kakao_flutter_sdk_user: ^1.9.6
  http: ^1.5.0
  google_sign_in: ^6.1.5
  mjpeg_view: ^1.0.1
  flutter_tts: ^4.2.3
  webview_flutter: ^4.13.0
  webview_flutter_web: ^0.2.3+4
  flutter_webrtc: ^1.2.0
  speech_to_text: ^7.3.0
  string_similarity: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/refuel_robot.png

# flutter_launcher_icons 설정
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48